APP_NAME: offshorelicense
SHORT_PROJECT_NAME: offshorelicense
APP_KEY: 'QdLTvhXaMe6Fo7YiCfbS7D7oK7LzMy22'
APP_LOCALE: en
LOG_CHANNEL: daily
FILESYSTEM_DRIVER: local

DATABASE_TYPE: mysql
DB_CONNECTION: mysql

NODE_VERSION: 18
MYSQL_VERSION: '5.7'
PGSQL_VERSION: 15
MARIADB_VERSION: 11.1.2

APP_CODE_PATH_CONTAINER: /var/www/html
